import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const isDarkMode = false; // 你可以根据实际情况设置

  return (
    <html lang="en" className={isDarkMode ? 'dark' : ''}>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
